Demo page to gh-pages
darcyclarke/Detect.js pull request #52
Opened 2017-02-13 20:55 UTC by EL-shadow

Demo page for testing in browser resolve #45 
 from https://el-shadow.github.io/Detect.js/
to https://darcyclarke.github.io/Detect.js/

2017-02-13 22:39 UTC, AdrianoCahete commented
I think you can use the lib from master branch, but i don't know how. I'll search for, it's easy to maintain udapted.

2017-02-14 06:52 UTC, julmot commented
With RawGit

2017-02-14 19:54 UTC, EL-shadow commented
fixed

2017-02-15 21:04 UTC, AdrianoCahete requested changes

2017-02-15 21:04 UTC, AdrianoCahete commented on index.html
> +    <script src="https://rawgit.com/darcyclarke/Detect.js/master/detect.js"></script>
In RawGit, they tell us to use cdn endpoint to create cache. But the cache don't expire, so we need to point not to master file, but the release/tag file: `https://cdn.rawgit.com/darcyclarke/Detect.js/v2.2.2/detect.js`

2017-02-15 21:05 UTC, AdrianoCahete commented
I didn't test, just point out the file change. Please, test before.

2017-02-16 20:08 UTC, EL-shadow commented
I update rawgit link to cdn tagged version and test page  - correctly work.

2017-02-18 17:51 UTC, AdrianoCahete approved these changes

2017-02-18 17:51 UTC, AdrianoCahete commented
I'll try to test and merge to master this week.

2019-02-25 20:20 UTC, merged